### ISSUE TITLE
1.5.0.beta12版本支持

### ISSUE THREAD

**Issue by 0es** [fantasticfears/chinese-share-links#6]
按照说明安装并且清空缓存重试之后，插件成功显示，但是后台设置没有显示多出的分享。

**Comment by fantasticfears** [comment]
直接输入 `weibo`、`renren`或者`wechat`就好了

**Comment by 0es** [comment]
成功解决，十分感谢。另外想问一下主分支为什么没有添加qq空间支持？

**Comment by fantasticfears** [comment]
QQ 空间没有链接支持的方法吧。不是程序 bug 麻烦您到中文论坛提意见和相关的文档。
